import { useCallback,useEffect,useState } from 'react'
import { ArrowLeft,CheckCircle2,CircleDollarSign,FileUp,Plus,ReceiptText,Send,XCircle } from 'lucide-react'
import { Link,useParams } from 'react-router-dom'
import { toast } from 'sonner'
import Badge from '../components/common/Badge'
import LoadingState from '../components/common/LoadingState'
import Modal from '../components/common/Modal'
import { useAuth } from '../contexts/AuthContext'
import { expenseService } from '../services/expenseService'
import { DOCUMENT_TYPES,EXPENSE_STATUS_COLORS,PAYMENT_METHODS,expenseStatusLabel,money } from '../utils/expenseConstants'

const initialPayment={payment_date:new Date().toISOString().slice(0,10),payment_method:'bank_transfer',amount:'',bank_name:'',transaction_reference:'',recipient_name:'',file:null}
const initialItem={expense_date:new Date().toISOString().slice(0,10),description:'',vendor_name:'',invoice_number:'',quantity:1,unit_price:'',file:null}
export default function ExpenseRequestDetailPage(){
 const {id}=useParams();const {profile,hasPermission}=useAuth();const [request,setRequest]=useState(null);const [loading,setLoading]=useState(true);const [dialog,setDialog]=useState(null);const [decision,setDecision]=useState({type:'approved',comment:'',approved_amount:''});const [payment,setPayment]=useState(initialPayment);const [item,setItem]=useState(initialItem);const [document,setDocument]=useState({document_type:'receipt',file:null});const [verification,setVerification]=useState({receipts_complete:false,receipt_total_matches:false,returned_amount_correct:false,category_valid:false,within_approved_amount:false,notes:''})
 const load=useCallback(async()=>{setLoading(true);const result=await expenseService.getRequest(id);if(result.error)toast.error(result.error.message);setRequest(result.data);setLoading(false)},[id]);useEffect(()=>{load()},[load]);if(loading||!request)return <LoadingState/>
 const act=async()=>{const result=await expenseService.decide(id,decision.type,decision.comment,decision.approved_amount||null);if(result.error)return toast.error(result.error.message);toast.success('បានកត់ត្រាសេចក្ដីសម្រេច');setDialog(null);load()}
 const submit=async()=>{const result=await expenseService.submit(id);if(result.error)return toast.error(result.error.message);toast.success('បានដាក់ស្នើ');load()}
 const pay=async e=>{e.preventDefault();if(!payment.file)return toast.error('សូមភ្ជាប់ភស្តុតាងទូទាត់');const upload=await expenseService.upload(payment.file,id,'payments');if(upload.error)return toast.error(upload.error.message);const result=await expenseService.pay(id,{...payment,attachment:upload.data.path});if(result.error)return toast.error(result.error.message);toast.success('បានកត់ត្រាការទូទាត់');setDialog(null);setPayment(initialPayment);load()}
 const addItem=async e=>{e.preventDefault();if(!item.file)return toast.error('សូមភ្ជាប់បង្កាន់ដៃ/វិក្កយបត្រ');const upload=await expenseService.upload(item.file,id,'items');if(upload.error)return toast.error(upload.error.message);const result=await expenseService.addItem({...item,file:undefined,attachment:upload.data.path,expense_request_id:id});if(result.error)return toast.error(result.error.message);toast.success('បានបន្ថែមចំណាយជាក់ស្តែង');setDialog(null);setItem(initialItem);load()}
 const addDocument=async e=>{e.preventDefault();if(!document.file)return;const upload=await expenseService.upload(document.file,id);if(upload.error)return toast.error(upload.error.message);const result=await expenseService.addDocument({expense_request_id:id,document_type:document.document_type,file_name:document.file.name,file_path:upload.data.path});if(result.error)return toast.error(result.error.message);toast.success('បានបញ្ចូលឯកសារ');setDialog(null);load()}
 const verify=async event=>{event.preventDefault();const result=await expenseService.verify(id,verification);if(result.error)return toast.error(result.error.message);toast.success('បានរក្សាទុកការផ្ទៀងផ្ទាត់');setDialog(null);load()};const complete=async()=>{const result=await expenseService.complete(id);if(result.error)return toast.error(result.error.message);toast.success('បានបិទបញ្ជីចំណាយ');load()};const pending=request.approvals?.find(x=>x.decision==='pending');const canApprove=hasPermission('expenses.approve')&&request.requested_by!==profile?.id&&['submitted','under_review'].includes(request.status);const unpaid=Number(request.approved_amount)-Number(request.amount_received);const verified=request.verification&&request.verification.receipts_complete&&request.verification.receipt_total_matches&&request.verification.returned_amount_correct&&request.verification.category_valid&&request.verification.within_approved_amount
 return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Link className="rounded-xl border bg-white p-2" to="/expenses/requests"><ArrowLeft/></Link><div><div className="flex gap-2"><h1 className="text-2xl font-bold">{request.request_code}</h1><Badge className={EXPENSE_STATUS_COLORS[request.status]}>{expenseStatusLabel(request.status)}</Badge></div><p className="text-sm text-slate-500">{request.province?.name_kh} · {request.project?.name_kh}</p></div></div><div className="flex flex-wrap gap-2">{['draft','returned'].includes(request.status)&&request.requested_by===profile?.id&&<><button className="btn-secondary" onClick={()=>setDialog('document')}><FileUp size={17}/>ឯកសារ</button><button className="btn-primary" onClick={submit}><Send size={17}/>ដាក់ស្នើ</button></>}{canApprove&&<><button className="btn-secondary text-orange-700" onClick={()=>{setDecision({type:'returned',comment:'',approved_amount:''});setDialog('decision')}}>ត្រឡប់</button><button className="btn-secondary text-red-700" onClick={()=>{setDecision({type:'rejected',comment:'',approved_amount:''});setDialog('decision')}}><XCircle size={17}/>បដិសេធ</button><button className="btn-primary" onClick={()=>{setDecision({type:'approved',comment:'',approved_amount:request.requested_amount});setDialog('decision')}}><CheckCircle2 size={17}/>អនុម័តកម្រិត {pending?.approval_level}</button></>}{hasPermission('expenses.pay')&&['approved','payment_processing'].includes(request.status)&&<button className="btn-primary" onClick={()=>setDialog('payment')}><CircleDollarSign size={17}/>ទូទាត់</button>}{hasPermission('expenses.actual')&&['paid','payment_processing'].includes(request.status)&&request.requested_by===profile?.id&&<button className="btn-primary" onClick={()=>setDialog('item')}><ReceiptText size={17}/>កត់ត្រាចំណាយ</button>}{hasPermission('expenses.verify')&&request.status==='paid'&&<button className="btn-secondary" onClick={()=>{setVerification(request.verification||verification);setDialog('verification')}}><CheckCircle2 size={17}/>ផ្ទៀងផ្ទាត់</button>}{hasPermission('expenses.complete')&&request.status==='paid'&&<button className="btn-primary" disabled={!verified} title={!verified?'សូមផ្ទៀងផ្ទាត់ឱ្យគ្រប់ចំណុច':''} onClick={complete}><CheckCircle2 size={17}/>បិទបញ្ជី</button>}</div></div>
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{[['ស្នើសុំ',request.requested_amount],['អនុម័ត',request.approved_amount],['ទទួលបាន',request.amount_received],['ចំណាយជាក់ស្តែង',request.actual_amount],['ត្រូវប្រគល់វិញ',request.returned_amount]].map(([x,v])=><div className="card p-4" key={x}><p className="text-sm text-slate-500">{x}</p><p className="text-xl font-bold">{money(v)}</p></div>)}</div>
 <div className="grid gap-4 xl:grid-cols-3"><div className="card space-y-3 p-5 xl:col-span-2"><h2 className="font-bold">ព័ត៌មានសំណើ</h2><p><b>គោលបំណង៖</b> {request.purpose}</p><div className="grid gap-2 text-sm md:grid-cols-2"><p><b>កាលបរិច្ឆេទ៖</b> {request.request_date}</p><p><b>ប្រភេទ៖</b> {request.category?.name_kh}</p><p><b>អ្នកស្នើ៖</b> {request.requester?.full_name}</p><p><b>មិនទាន់ទូទាត់៖</b> {money(unpaid)}</p></div></div><div className="card p-5"><h2 className="mb-3 font-bold">ដំណាក់កាលអនុម័ត</h2><div className="space-y-2">{request.approvals?.map(row=><div className="rounded-xl bg-slate-50 p-3 text-sm" key={row.id}><div className="flex justify-between"><b>កម្រិត {row.approval_level}</b><span className="capitalize">{row.decision}</span></div><p className="text-slate-500">{row.approver_role} {row.approver?.full_name&&`· ${row.approver.full_name}`}</p>{row.comment&&<p>{row.comment}</p>}</div>)}</div></div></div>
 <div className="grid gap-4 xl:grid-cols-2"><Section title="ការទូទាត់" rows={request.payments} empty="មិនទាន់មានការទូទាត់" render={x=><div><b>{x.payment_code}</b><p className="text-sm text-slate-500">{x.payment_date} · {x.recipient_name}</p><p className="font-bold text-green-700">{money(x.amount)}</p></div>}/><Section title="ចំណាយជាក់ស្តែង" rows={request.items} empty="មិនទាន់មានចំណាយ" render={x=><div><b>{x.description}</b><p className="text-sm text-slate-500">{x.vendor_name} · {x.invoice_number}</p><p className="font-bold">{money(x.amount)}</p></div>}/></div><Section title="ឯកសារគាំទ្រ" rows={request.documents} empty="មិនមានឯកសារ" render={x=><div><b>{x.file_name}</b><p className="text-sm text-slate-500">{x.document_type}</p></div>}/>
 <Modal open={dialog==='decision'} onClose={()=>setDialog(null)} title="សេចក្ដីសម្រេច"><div className="space-y-4">{decision.type==='approved'&&<div><label className="label">ចំនួនអនុម័ត</label><input className="field" type="number" value={decision.approved_amount} onChange={e=>setDecision({...decision,approved_amount:e.target.value})}/></div>}<div><label className="label">មតិយោបល់</label><textarea className="field" value={decision.comment} onChange={e=>setDecision({...decision,comment:e.target.value})}/></div><button className="btn-primary ml-auto" onClick={act}>បញ្ជាក់</button></div></Modal>
 <Modal open={dialog==='payment'} onClose={()=>setDialog(null)} title="កត់ត្រាការទូទាត់"><form className="grid gap-3 md:grid-cols-2" onSubmit={pay}><Input label="កាលបរិច្ឆេទ" type="date" value={payment.payment_date} set={v=>setPayment({...payment,payment_date:v})}/><div><label className="label">វិធីទូទាត់</label><select className="field" value={payment.payment_method} onChange={e=>setPayment({...payment,payment_method:e.target.value})}>{PAYMENT_METHODS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><Input label={`ចំនួន (នៅសល់ ${money(unpaid)})`} type="number" value={payment.amount} set={v=>setPayment({...payment,amount:v})}/><Input label="អ្នកទទួល" value={payment.recipient_name} set={v=>setPayment({...payment,recipient_name:v})}/><Input label="ធនាគារ" value={payment.bank_name} set={v=>setPayment({...payment,bank_name:v})}/><Input label="លេខយោង" value={payment.transaction_reference} set={v=>setPayment({...payment,transaction_reference:v})}/><input className="field md:col-span-2" type="file" accept=".pdf,image/*" onChange={e=>setPayment({...payment,file:e.target.files?.[0]})}/><button className="btn-primary md:col-span-2">រក្សាទុក</button></form></Modal>
 <Modal open={dialog==='item'} onClose={()=>setDialog(null)} title="ចំណាយជាក់ស្តែង"><form className="grid gap-3 md:grid-cols-2" onSubmit={addItem}><Input label="កាលបរិច្ឆេទ" type="date" value={item.expense_date} set={v=>setItem({...item,expense_date:v})}/><Input label="លេខវិក្កយបត្រ" value={item.invoice_number} set={v=>setItem({...item,invoice_number:v})}/><Input label="បរិយាយ" value={item.description} set={v=>setItem({...item,description:v})}/><Input label="អ្នកផ្គត់ផ្គង់" value={item.vendor_name} set={v=>setItem({...item,vendor_name:v})}/><Input label="បរិមាណ" type="number" value={item.quantity} set={v=>setItem({...item,quantity:v})}/><Input label="តម្លៃឯកតា" type="number" value={item.unit_price} set={v=>setItem({...item,unit_price:v})}/><input className="field md:col-span-2" type="file" accept=".pdf,image/*" onChange={e=>setItem({...item,file:e.target.files?.[0]})}/><button className="btn-primary md:col-span-2"><Plus size={17}/>បន្ថែម</button></form></Modal>
 <Modal open={dialog==='document'} onClose={()=>setDialog(null)} title="បញ្ចូលឯកសារ"><form className="space-y-3" onSubmit={addDocument}><select className="field" value={document.document_type} onChange={e=>setDocument({...document,document_type:e.target.value})}>{DOCUMENT_TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input className="field" type="file" accept=".pdf,image/*" onChange={e=>setDocument({...document,file:e.target.files?.[0]})}/><button className="btn-primary">បញ្ចូលឯកសារ</button></form></Modal>
 <Modal open={dialog==='verification'} onClose={()=>setDialog(null)} title="ផ្ទៀងផ្ទាត់មុនបិទបញ្ជី"><form className="space-y-3" onSubmit={verify}>{[['receipts_complete','ឯកសារ និងបង្កាន់ដៃមានគ្រប់'],['receipt_total_matches','សរុបបង្កាន់ដៃត្រូវនឹងចំណាយជាក់ស្តែង'],['returned_amount_correct','ប្រាក់ត្រូវប្រគល់វិញគណនាត្រឹមត្រូវ'],['category_valid','ប្រភេទចំណាយត្រឹមត្រូវ'],['within_approved_amount','ចំណាយមិនលើសចំនួនអនុម័ត']].map(([key,label])=><label key={key} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 ${verification[key]?'border-green-300 bg-green-50':'bg-white'}`}><input type="checkbox" checked={verification[key]} onChange={e=>setVerification({...verification,[key]:e.target.checked})}/><span className="text-sm font-medium">{label}</span></label>)}<textarea className="field" placeholder="កំណត់សម្គាល់..." value={verification.notes||''} onChange={e=>setVerification({...verification,notes:e.target.value})}/><button className="btn-primary w-full">រក្សាទុកការផ្ទៀងផ្ទាត់</button></form></Modal></div>
}
function Section({title,rows=[],empty,render}){return <div className="card p-5"><h2 className="mb-3 font-bold">{title}</h2>{rows.length===0?<p className="text-sm text-slate-500">{empty}</p>:<div className="divide-y">{rows.map(row=><div className="py-3" key={row.id}>{render(row)}</div>)}</div>}</div>}
function Input({label,type='text',value,set}){return <div><label className="label">{label}</label><input required className="field" type={type} step={type==='number'?'0.01':undefined} value={value} onChange={e=>set(e.target.value)}/></div>}
