import { useCallback,useEffect,useState } from 'react'
import { ChevronLeft,ChevronRight,Eye,Plus,Search } from 'lucide-react'
import { Link } from 'react-router-dom'
import { toast } from 'sonner'
import Badge from '../components/common/Badge'
import EmptyState from '../components/common/EmptyState'
import LoadingState from '../components/common/LoadingState'
import { useAuth } from '../contexts/AuthContext'
import { expenseService } from '../services/expenseService'
import { EXPENSE_STATUSES,EXPENSE_STATUS_COLORS,expenseStatusLabel,money } from '../utils/expenseConstants'

export default function ExpenseRequestsPage(){
 const {hasPermission}=useAuth();const [filters,setFilters]=useState({search:'',status:'',provinceId:'',page:1,pageSize:10});const [rows,setRows]=useState([]);const [count,setCount]=useState(0);const [loading,setLoading]=useState(true);const [lookups,setLookups]=useState({provinces:[]})
 const load=useCallback(async()=>{setLoading(true);const result=await expenseService.requests(filters);if(result.error)toast.error(result.error.message);setRows(result.data||[]);setCount(result.count||0);setLoading(false)},[filters])
 useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[load]);useEffect(()=>{expenseService.lookups().then(setLookups)},[]);const change=e=>setFilters(current=>({...current,[e.target.name]:e.target.value,page:1}));const pages=Math.max(1,Math.ceil(count/filters.pageSize))
 return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">សំណើចំណាយ</h1><p className="text-sm text-slate-500">តាមដានការស្នើសុំ អនុម័ត ទូទាត់ និងបិទបញ្ជី</p></div>{hasPermission('expenses.create')&&<Link to="/expenses/requests/new" className="btn-primary"><Plus size={18}/>បង្កើតសំណើ</Link>}</div>
 <div className="card grid gap-3 p-4 md:grid-cols-3"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input className="field pl-10" name="search" value={filters.search} onChange={change} placeholder="លេខកូដ ឬគោលបំណង..."/></div><select className="field" name="provinceId" value={filters.provinceId} onChange={change}><option value="">ខេត្តទាំងអស់</option>{lookups.provinces?.map(x=><option key={x.id} value={x.id}>{x.name_kh}</option>)}</select><select className="field" name="status" value={filters.status} onChange={change}><option value="">ស្ថានភាពទាំងអស់</option>{EXPENSE_STATUSES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>
 <div className="card overflow-hidden">{loading?<LoadingState/>:rows.length===0?<EmptyState title="មិនមានសំណើចំណាយ"/>:<><div className="overflow-x-auto"><table className="w-full min-w-[1100px]"><thead className="sticky top-0 bg-slate-50 text-left text-xs text-slate-500"><tr>{['ល.រ','លេខកូដ','កាលបរិច្ឆេទ','ខេត្ត','គោលបំណង','ស្នើសុំ','អនុម័ត','ជាក់ស្តែង','ស្ថានភាព','អ្នកស្នើ',''].map(x=><th className="table-cell" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{rows.map((row,i)=><tr key={row.id}><td className="table-cell">{(filters.page-1)*filters.pageSize+i+1}</td><td className="table-cell font-mono font-semibold text-blue-700">{row.request_code}</td><td className="table-cell">{row.request_date}</td><td className="table-cell">{row.province?.name_kh}</td><td className="table-cell max-w-64 truncate">{row.purpose}</td><td className="table-cell">{money(row.requested_amount)}</td><td className="table-cell">{money(row.approved_amount)}</td><td className="table-cell">{money(row.actual_amount)}</td><td className="table-cell"><Badge className={EXPENSE_STATUS_COLORS[row.status]}>{expenseStatusLabel(row.status)}</Badge></td><td className="table-cell">{row.requester?.full_name}</td><td className="table-cell"><Link className="text-blue-600" to={`/expenses/requests/${row.id}`}><Eye size={18}/></Link></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t p-3 text-sm"><span>សរុប {count}</span><div className="flex gap-2"><button className="btn-secondary px-3" disabled={filters.page<=1} onClick={()=>setFilters(x=>({...x,page:x.page-1}))}><ChevronLeft size={17}/></button><button className="btn-secondary px-3" disabled={filters.page>=pages} onClick={()=>setFilters(x=>({...x,page:x.page+1}))}><ChevronRight size={17}/></button></div></div></>}</div></div>
}
