import { useEffect,useState } from 'react'
import { AlertTriangle,BarChart3,CheckCircle2,CircleDollarSign,Clock3,Landmark,ReceiptText,WalletCards,XCircle } from 'lucide-react'
import { Bar,BarChart,CartesianGrid,Cell,Legend,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from 'recharts'
import LoadingState from '../components/common/LoadingState'
import { expenseService } from '../services/expenseService'
import { expenseStatusLabel,money } from '../utils/expenseConstants'

export default function ExpenseDashboardPage(){
 const [data,setData]=useState(null);const [alerts,setAlerts]=useState([]);const [missions,setMissions]=useState([]);const [year,setYear]=useState(new Date().getFullYear())
 useEffect(()=>{Promise.all([expenseService.dashboard({fiscalYear:year}),expenseService.budgetAlerts(),expenseService.missionSummary()]).then(([dashboard,alertResult,missionResult])=>{setData(dashboard);setAlerts((alertResult.data||[]).filter(item=>Number(item.fiscal_year)===Number(year)));setMissions(missionResult.data||[])})},[year])
 if(!data)return <LoadingState label="កំពុងទាញទិន្នន័យចំណាយ..."/>
 const cards=[['ថវិកាសរុប',data.stats.totalBudget,Landmark,'text-blue-700 bg-blue-50'],['បានអនុម័ត',data.stats.approved,CheckCircle2,'text-emerald-700 bg-emerald-50'],['បានទូទាត់',data.stats.paid,WalletCards,'text-violet-700 bg-violet-50'],['ចំណាយជាក់ស្តែង',data.stats.actual,ReceiptText,'text-cyan-700 bg-cyan-50'],['ថវិកានៅសល់',data.stats.remaining,CircleDollarSign,'text-green-700 bg-green-50'],['កំពុងរង់ចាំ',data.stats.pending,Clock3,'text-amber-700 bg-amber-50'],['បដិសេធ',data.stats.rejected,XCircle,'text-red-700 bg-red-50'],['បានបញ្ចប់',data.stats.completed,BarChart3,'text-slate-700 bg-slate-100']]
 const provinceMap=new Map();data.budgets.forEach(row=>{const current=provinceMap.get(row.province?.name_kh)||{name:row.province?.name_kh,budget:0,actual:0};current.budget+=Number(row.approved_amount)+Number(row.revised_amount);current.actual+=Number(row.actual_expense_amount);provinceMap.set(current.name,current)})
 const statusMap=new Map();data.requests.forEach(row=>statusMap.set(expenseStatusLabel(row.status),(statusMap.get(expenseStatusLabel(row.status))||0)+1));const colors=['#2563eb','#16a34a','#f59e0b','#dc2626','#7c3aed','#0891b2']
 return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">ផ្ទាំងគ្រប់គ្រងចំណាយខេត្ត</h1><p className="text-sm text-slate-500">ស្ថានភាពថវិកា ការទូទាត់ និងចំណាយជាក់ស្តែង</p></div><input type="number" className="field w-32" value={year} onChange={e=>setYear(e.target.value)}/></div>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,Icon,tone],index)=><div className="card flex items-center gap-3 p-4" key={label}><div className={`grid size-11 place-items-center rounded-xl ${tone}`}><Icon size={21}/></div><div><p className="text-sm text-slate-500">{label}</p><p className="text-xl font-bold">{index<5?money(value):value}</p></div></div>)}</div>
 {alerts.length>0&&<div className="card border-amber-200 p-4"><div className="mb-3 flex items-center gap-2"><AlertTriangle className="text-amber-600"/><h2 className="font-bold">ការព្រមានការប្រើប្រាស់ថវិកា</h2><span className="rounded-full bg-amber-100 px-2 py-0.5 text-xs font-bold text-amber-700">{alerts.length}</span></div><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{alerts.slice(0,6).map(item=><div key={item.id} className={`rounded-xl p-3 text-sm ${['critical','exceeded'].includes(item.alert_level)?'bg-red-50 text-red-800':'bg-amber-50 text-amber-800'}`}><div className="flex justify-between"><b>{item.province_name}</b><b>{item.usage_percentage}%</b></div><p>{item.project_name} · {item.category_name}</p><p>នៅសល់ {money(item.remaining_amount)}</p></div>)}</div></div>}
 {missions.length>0&&<div className="card overflow-hidden"><div className="border-b p-4"><h2 className="font-bold">សង្ខេបចំណាយបេសកកម្មតាម Sales</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[850px]"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr>{['Sales','បេសកកម្ម','កំពុងដំណើរការ','បានអនុម័ត','បានទូទាត់','ចំណាយពិត','ប្រគល់វិញ'].map(label=><th key={label} className="table-cell">{label}</th>)}</tr></thead><tbody className="divide-y">{missions.map(row=><tr key={row.sales_id}><td className="table-cell font-semibold">{row.sales_name}</td><td className="table-cell">{row.request_count}</td><td className="table-cell">{row.active_missions}</td><td className="table-cell">{money(row.approved_amount)}</td><td className="table-cell">{money(row.paid_amount)}</td><td className="table-cell">{money(row.actual_amount)}</td><td className="table-cell text-green-700">{money(row.returned_amount)}</td></tr>)}</tbody></table></div></div>}
 <div className="grid gap-4 xl:grid-cols-3"><div className="card p-4 xl:col-span-2"><h2 className="mb-4 font-bold">ថវិកាធៀបនឹងចំណាយតាមខេត្ត</h2><ResponsiveContainer width="100%" height={320}><BarChart data={[...provinceMap.values()]}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name" hide/><YAxis/><Tooltip formatter={money}/><Legend/><Bar dataKey="budget" name="ថវិកា" fill="#2563eb"/><Bar dataKey="actual" name="ចំណាយ" fill="#16a34a"/></BarChart></ResponsiveContainer></div><div className="card p-4"><h2 className="mb-4 font-bold">ស្ថានភាពសំណើ</h2><ResponsiveContainer width="100%" height={320}><PieChart><Pie data={[...statusMap].map(([name,value])=>({name,value}))} dataKey="value" nameKey="name" outerRadius={105}>{[...statusMap].map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></div></div></div>
}
