import { useCallback, useEffect, useState } from 'react'
import { CalendarRange, Pencil, Plus, UserRound, WalletCards } from 'lucide-react'
import { toast } from 'sonner'
import EmptyState from '../components/common/EmptyState'
import LoadingState from '../components/common/LoadingState'
import Modal from '../components/common/Modal'
import { useAuth } from '../contexts/AuthContext'
import { fuelBudgetService } from '../services/fuelBudgetService'

const empty = { fiscal_year: new Date().getFullYear(), fiscal_month: '', fiscal_week: '', province_id: '', sales_user_id: '', allocated_amount: '', currency: 'KHR', status: 'active', note: '' }
const money = value => new Intl.NumberFormat('km-KH', { maximumFractionDigits: 2 }).format(Number(value) || 0)
const years = Array.from({ length: 6 }, (_, index) => new Date().getFullYear() - 1 + index)

export default function FuelBudgetsPage() {
  const { hasPermission } = useAuth()
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [form, setForm] = useState(null); const [lookups, setLookups] = useState({ provinces: [], sales: [], plans: [] })
  const load = useCallback(async () => { setLoading(true); const result = await fuelBudgetService.list(); if (result.error) toast.error(result.error.message); setRows(result.data || []); setLoading(false) }, [])
  useEffect(() => { load(); Promise.all([fuelBudgetService.provinces(), fuelBudgetService.sales()]).then(([provinces, sales]) => setLookups(current => ({ ...current, provinces: provinces.data || [], sales: sales.data || [] }))) }, [load])
  const selectSales = async salesUserId => { const result = await fuelBudgetService.visitPlanLocations(salesUserId); setLookups(current => ({ ...current, plans: result.data || [] })); setForm(current => ({ ...current, sales_user_id: salesUserId, visit_plan_id: '', province_id: '' })) }
  const planOptions = (lookups.plans || []).filter(plan => { const date = new Date(`${plan.start_date}T00:00:00`); const week = isoWeek(date); return date.getFullYear() === Number(form?.fiscal_year) && (!form?.fiscal_month || date.getMonth() + 1 === Number(form.fiscal_month)) && (!form?.fiscal_week || week === Number(form.fiscal_week)) })
  const selectPlan = visitPlanId => { const plan = lookups.plans.find(item => item.id === visitPlanId); const province = lookups.provinces.find(item => [item.name_kh,item.name_en].filter(Boolean).some(name => normalizeLocation(name) === normalizeLocation(plan?.province))); setForm(current => ({ ...current, visit_plan_id: visitPlanId, province_id: province?.id || '' })); if (plan && !province) toast.error(`ទីតាំង ${plan.province} មិនត្រូវនឹងបញ្ជីខេត្ត`) }
  const edit = async row => { const result = await fuelBudgetService.visitPlanLocations(row.sales_user_id); setLookups(current => ({ ...current, plans: result.data || [] })); setForm({ ...row }) }
  const save = async event => { event.preventDefault(); const payload = { visit_plan_id: form.visit_plan_id, fiscal_year: Number(form.fiscal_year), fiscal_month: form.fiscal_month ? Number(form.fiscal_month) : null, fiscal_week: form.fiscal_week ? Number(form.fiscal_week) : null, province_id: form.province_id, sales_user_id: form.sales_user_id, allocated_amount: Number(form.allocated_amount), currency: form.currency, status: form.status || 'active', note: form.note || null }; const result = form.id ? await fuelBudgetService.update(form.id, payload) : await fuelBudgetService.save(payload); if (result.error) return toast.error(result.error.message); toast.success('បានរក្សាទុកថវិកាសាំង'); setForm(null); load() }
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">ថវិកាសាំង</h1><p className="text-sm text-slate-500">គ្រប់គ្រងកម្រិតថវិកាតាមរយៈពេល Sales និងខេត្ត</p></div>{hasPermission('fuel.budgets.manage') && <button className="btn-primary" onClick={() => setForm(empty)}><Plus size={18}/>កំណត់ថវិកា</button>}</div>
    <div className="grid gap-3 md:grid-cols-3"><Summary icon={WalletCards} label="ថវិកាសរុប" value={money(rows.reduce((sum,row)=>sum+Number(row.allocated_amount),0))}/><Summary icon={CalendarRange} label="កំណត់ត្រាថវិកា" value={rows.length}/><Summary icon={UserRound} label="Sales មានថវិកា" value={new Set(rows.map(row=>row.sales_user_id)).size}/></div>
    <div className="card overflow-hidden">{loading ? <LoadingState/> : rows.length === 0 ? <EmptyState title="មិនទាន់មានថវិកាសាំង"/> : <div className="overflow-x-auto"><table className="w-full min-w-[1150px]"><thead className="sticky top-0 bg-slate-50 text-left text-xs text-slate-500"><tr>{['រយៈពេល','Sales','ផែនការចុះ','ខេត្ត','ថវិកា','បានប្រើ','នៅសល់','រូបិយប័ណ្ណ','ស្ថានភាព','សកម្មភាព'].map(label => <th className="table-cell" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y">{rows.map(row => <tr key={row.id}><td className="table-cell font-semibold">{row.fiscal_year} · {row.fiscal_month ? `ខែ ${row.fiscal_month}` : 'ពេញឆ្នាំ'}{row.fiscal_week ? ` · សប្តាហ៍ ${row.fiscal_week}` : ''}</td><td className="table-cell">{row.sales_name}</td><td className="table-cell max-w-56 truncate">{row.visit_plan_title}</td><td className="table-cell">{row.province_name_kh}</td><td className="table-cell font-bold">{money(row.allocated_amount)}</td><td className="table-cell text-amber-700">{money(row.used_amount)}</td><td className="table-cell font-bold text-green-700">{money(row.remaining_amount)}</td><td className="table-cell">{row.currency}</td><td className="table-cell"><span className="rounded-full bg-green-50 px-2 py-1 text-xs font-semibold text-green-700">{row.status}</span></td><td className="table-cell">{hasPermission('fuel.budgets.manage') && <button className="rounded-lg p-2 text-blue-600 hover:bg-blue-50" onClick={() => edit(row)}><Pencil size={17}/></button>}</td></tr>)}</tbody></table></div>}</div>
    <Modal open={Boolean(form)} onClose={() => setForm(null)} title={form?.id ? 'កែថវិកាសាំង' : 'កំណត់ថវិកាសាំង'} size="max-w-3xl"><form className="space-y-5" onSubmit={save}>
      <Section number="1" title="រយៈពេលថវិកា" description="អាចកំណត់ជាប្រចាំឆ្នាំ ប្រចាំខែ ឬប្រចាំសប្តាហ៍។"><div className="grid gap-4 md:grid-cols-3"><Field label="ឆ្នាំ *"><select required className="field" value={form?.fiscal_year || ''} onChange={event => setForm({ ...form, fiscal_year: event.target.value })}>{years.map(year => <option key={year}>{year}</option>)}</select></Field><Field label="ខែ"><select className="field" value={form?.fiscal_month || ''} onChange={event => setForm({ ...form, fiscal_month: event.target.value })}><option value="">ពេញឆ្នាំ</option>{Array.from({length:12},(_,index)=><option key={index+1} value={index+1}>ខែ {index+1}</option>)}</select></Field><Field label="សប្តាហ៍"><select className="field" value={form?.fiscal_week || ''} onChange={event => setForm({ ...form, fiscal_week: event.target.value })}><option value="">មិនកំណត់</option>{Array.from({length:53},(_,index)=><option key={index+1} value={index+1}>សប្តាហ៍ទី {index+1}</option>)}</select></Field></div></Section>
      <Section number="2" title="វិសាលភាពថវិកា" description="ជ្រើស Sales មុន រួចជ្រើសផែនការដែលស្ថិតក្នុងរយៈពេលខាងលើ។"><div className="grid gap-4 md:grid-cols-2"><Field label="Sales *"><select required className="field" value={form?.sales_user_id || ''} onChange={event => selectSales(event.target.value)}><option value="">ជ្រើសរើស Sales</option>{lookups.sales.map(item => <option key={item.id} value={item.id}>{item.full_name}</option>)}</select></Field><Field label="ផែនការចុះ *"><select required disabled={!form?.sales_user_id} className="field disabled:bg-slate-100" value={form?.visit_plan_id || ''} onChange={event => selectPlan(event.target.value)}><option value="">{form?.sales_user_id ? 'ជ្រើសរើសផែនការចុះ' : 'សូមជ្រើស Sales ជាមុន'}</option>{planOptions.map(plan => <option key={plan.id} value={plan.id}>{plan.title} · {plan.province}</option>)}</select><p className="mt-1 text-xs text-slate-500">រកឃើញ {planOptions.length} ផែនការក្នុងរយៈពេលនេះ</p></Field></div></Section>
      <Section number="3" title="ចំនួន និងលក្ខខណ្ឌ" description="បញ្ចូលចំនួនថវិកា រូបិយប័ណ្ណ និងកំណត់សម្គាល់។"><div className="grid gap-4 md:grid-cols-2"><Field label="ចំនួនថវិកា *"><input required min="0.01" step="0.01" type="number" className="field" value={form?.allocated_amount || ''} onChange={event => setForm({ ...form, allocated_amount: event.target.value })}/></Field><Field label="រូបិយប័ណ្ណ"><select className="field" value={form?.currency || 'KHR'} onChange={event => setForm({ ...form, currency: event.target.value })}><option>KHR</option><option>USD</option></select></Field><div className="md:col-span-2"><Field label="កំណត់សម្គាល់"><textarea rows="2" className="field" value={form?.note || ''} onChange={event => setForm({ ...form, note: event.target.value })}/></Field></div></div></Section>
      <div className="flex justify-end gap-2 border-t pt-4"><button type="button" className="btn-secondary" onClick={() => setForm(null)}>បោះបង់</button><button className="btn-primary">រក្សាទុកថវិកា</button></div>
    </form></Modal>
  </div>
}
function Field({ label, children }) { return <div><label className="label">{label}</label>{children}</div> }
function Section({ number, title, description, children }) { return <section className="rounded-2xl border p-4"><div className="mb-4 flex gap-3"><span className="grid size-8 place-items-center rounded-full bg-blue-600 text-sm font-bold text-white">{number}</span><div><h3 className="font-bold">{title}</h3><p className="text-xs text-slate-500">{description}</p></div></div>{children}</section> }
function Summary({ icon: Icon, label, value }) { return <div className="card flex items-center gap-3 p-4"><span className="grid size-11 place-items-center rounded-xl bg-blue-50 text-blue-600"><Icon size={21}/></span><div><p className="text-xs text-slate-500">{label}</p><p className="text-xl font-bold">{value}</p></div></div> }
function isoWeek(date) { const value = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate())); value.setUTCDate(value.getUTCDate() + 4 - (value.getUTCDay() || 7)); const start = new Date(Date.UTC(value.getUTCFullYear(), 0, 1)); return Math.ceil((((value - start) / 86400000) + 1) / 7) }
function normalizeLocation(value = '') { return value.trim().toLowerCase().replace(/^(ខេត្ត|រាជធានី)/, '').replace(/\s+/g, '') }
