import { useCallback, useEffect, useMemo, useState } from 'react'
import { Banknote, Fuel, Pencil, Plus, Search, UserRound, WalletCards } from 'lucide-react'
import { toast } from 'sonner'
import EmptyState from '../components/common/EmptyState'
import LoadingState from '../components/common/LoadingState'
import Modal from '../components/common/Modal'
import { useAuth } from '../contexts/AuthContext'
import { fuelBudgetService } from '../services/fuelBudgetService'

const empty = { budget_scope: 'province', budget_date: new Date().toISOString().slice(0, 10), fiscal_year: new Date().getFullYear(), fiscal_month: new Date().getMonth() + 1, province_id: '', sales_user_id: '', visit_plan_id: '', allocated_amount: '', currency: 'KHR', status: 'active', note: '' }
const money = value => new Intl.NumberFormat('km-KH', { maximumFractionDigits: 2 }).format(Number(value) || 0)
const years = Array.from({ length: 6 }, (_, index) => new Date().getFullYear() - 1 + index)

export default function FuelBudgetsPage() {
  const { hasPermission } = useAuth()
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [form, setForm] = useState(null); const [lookups, setLookups] = useState({ provinces: [], sales: [], plans: [] })
  const [filters, setFilters] = useState({ search: '', fiscal_year: '', fiscal_month: '', sales_user_id: '', status: '' })
  const load = useCallback(async () => { setLoading(true); const result = await fuelBudgetService.list(); if (result.error) toast.error(result.error.message); setRows(result.data || []); setLoading(false) }, [])
  useEffect(() => { load(); Promise.all([fuelBudgetService.provinces(), fuelBudgetService.sales()]).then(([provinces, sales]) => setLookups(current => ({ ...current, provinces: provinces.data || [], sales: sales.data || [] }))) }, [load])
  const filteredRows = useMemo(() => rows.filter(row => {
    const search = filters.search.trim().toLowerCase()
    const haystack = [row.sales_name, row.visit_plan_title, row.province_name_kh, row.currency, row.status].filter(Boolean).join(' ').toLowerCase()
    return (!search || haystack.includes(search))
      && (!filters.fiscal_year || Number(row.fiscal_year) === Number(filters.fiscal_year))
      && (!filters.fiscal_month || Number(row.fiscal_month || 0) === Number(filters.fiscal_month))
      && (!filters.sales_user_id || row.sales_user_id === filters.sales_user_id)
      && (!filters.status || row.status === filters.status)
  }), [filters, rows])
  const latestBalanceRows = useMemo(() => {
    const bySalesCurrency = new Map()
    filteredRows.forEach(row => {
      const key = `${row.sales_user_id || ''}:${row.currency || ''}`
      const current = bySalesCurrency.get(key)
      if (!current || compareBudgetOrder(row, current) > 0) bySalesCurrency.set(key, row)
    })
    return Array.from(bySalesCurrency.values())
  }, [filteredRows])
  const selectSales = async salesUserId => { const result = await fuelBudgetService.visitPlans(salesUserId); setLookups(current => ({ ...current, plans: result.data || [] })); setForm(current => ({ ...current, sales_user_id: salesUserId, visit_plan_id: '' })); if (result.error) toast.error(result.error.message) }
  const planOptions = lookups.plans || []
  const selectScope = budgetScope => setForm(current => ({ ...current, budget_scope: budgetScope, visit_plan_id: budgetScope === 'province' ? '' : current.visit_plan_id }))
  const selectPlan = visitPlanId => { const plan = lookups.plans.find(item => item.id === visitPlanId); const province = lookups.provinces.find(item => [item.name_kh,item.name_en].filter(Boolean).some(name => normalizeLocation(name) === normalizeLocation(plan?.province))); setForm(current => ({ ...current, visit_plan_id: visitPlanId, province_id: visitPlanId ? province?.id || current.province_id : current.province_id, fiscal_week: null })); if (plan && !province) toast.error(`ទីតាំង ${plan.province} មិនត្រូវនឹងបញ្ជីខេត្ត`) }
  const edit = async row => { const result = await fuelBudgetService.visitPlans(row.sales_user_id); setLookups(current => ({ ...current, plans: result.data || [] })); setForm({ ...row, budget_scope: row.visit_plan_id ? 'plan' : 'province', budget_date: row.budget_date || `${row.fiscal_year}-${String(row.fiscal_month || 1).padStart(2, '0')}-01` }); if (result.error) toast.error(result.error.message) }
  const save = async event => { event.preventDefault(); const budgetDate = new Date(`${form.budget_date}T00:00:00`); const payload = { budget_date: form.budget_date, visit_plan_id: form.budget_scope === 'plan' ? form.visit_plan_id || null : null, fiscal_year: budgetDate.getFullYear(), fiscal_month: budgetDate.getMonth() + 1, fiscal_week: null, province_id: form.province_id, sales_user_id: form.sales_user_id, allocated_amount: Number(form.allocated_amount), currency: form.currency, status: form.status || 'active', note: form.note || null }; const result = form.id ? await fuelBudgetService.update(form.id, payload) : await fuelBudgetService.save(payload); if (result.error) return toast.error(result.error.message); toast.success('បានរក្សាទុកថវិកាសាំង'); setForm(null); load() }
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">ថវិកាសាំង</h1><p className="text-sm text-slate-500">គ្រប់គ្រងកម្រិតថវិកាតាមរយៈពេល Sales និងខេត្ត</p></div>{hasPermission('fuel.budgets.manage') && <button className="btn-primary" onClick={() => setForm(empty)}><Plus size={18}/>កំណត់ថវិកា</button>}</div>
    <div className="card grid gap-3 p-4 md:grid-cols-5"><div className="relative md:col-span-2"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input className="field pl-10" placeholder="ស្វែងរក Sales / ផែនការ / ខេត្ត..." value={filters.search} onChange={event => setFilters({ ...filters, search: event.target.value })}/></div><select className="field" value={filters.sales_user_id} onChange={event => setFilters({ ...filters, sales_user_id: event.target.value })}><option value="">Sales ទាំងអស់</option>{lookups.sales.map(item => <option key={item.id} value={item.id}>{item.full_name}</option>)}</select><select className="field" value={filters.fiscal_year} onChange={event => setFilters({ ...filters, fiscal_year: event.target.value })}><option value="">ឆ្នាំទាំងអស់</option>{years.map(year => <option key={year} value={year}>{year}</option>)}</select><select className="field" value={filters.fiscal_month} onChange={event => setFilters({ ...filters, fiscal_month: event.target.value })}><option value="">ខែទាំងអស់</option><option value="0">ពេញឆ្នាំ</option>{Array.from({length:12},(_,index)=><option key={index+1} value={index+1}>ខែ {index+1}</option>)}</select><select className="field md:col-start-5" value={filters.status} onChange={event => setFilters({ ...filters, status: event.target.value })}><option value="">ស្ថានភាពទាំងអស់</option><option value="active">active</option><option value="inactive">inactive</option><option value="closed">closed</option></select></div>
    <div className="grid gap-3 md:grid-cols-4"><Summary icon={WalletCards} label="Top Up សរុប" value={money(filteredRows.reduce((sum,row)=>sum+Number(row.allocated_amount),0))}/><Summary icon={Fuel} label="បានប្រើសរុប" value={money(filteredRows.reduce((sum,row)=>sum+Number(row.used_amount),0))}/><Summary icon={Banknote} label="នៅសល់ចុងក្រោយ" value={money(latestBalanceRows.reduce((sum,row)=>sum+Number(row.remaining_amount),0))}/><Summary icon={UserRound} label="Sales មានថវិកា" value={new Set(filteredRows.map(row=>row.sales_user_id)).size}/></div>
    <div className="card overflow-hidden">{loading ? <LoadingState/> : rows.length === 0 ? <EmptyState title="មិនទាន់មានថវិកាសាំង"/> : filteredRows.length === 0 ? <EmptyState title="រកមិនឃើញថវិកាសាំងតាម filter"/> : <div className="overflow-x-auto"><table className="w-full min-w-[1250px]"><thead className="sticky top-0 bg-slate-50 text-left text-xs text-slate-500"><tr>{['ថ្ងៃថវិកា','Sales','ផែនការចុះ','ខេត្ត','Top Up','សល់មុន','សរុបប្រើបាន','បានប្រើ','នៅសល់','រូបិយប័ណ្ណ','ស្ថានភាព','សកម្មភាព'].map(label => <th className="table-cell" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y">{filteredRows.map(row => <tr key={row.id}><td className="table-cell font-semibold">{formatDate(row.budget_date) || `${row.fiscal_year} · ខែ ${row.fiscal_month}`}</td><td className="table-cell">{row.sales_name}</td><td className="table-cell max-w-56 truncate">{row.visit_plan_title || 'មិនភ្ជាប់ Plan'}</td><td className="table-cell">{row.province_name_kh}</td><td className="table-cell font-bold">{money(row.allocated_amount)}</td><td className="table-cell text-blue-700">{money(row.carry_forward_amount)}</td><td className="table-cell font-semibold">{money(row.available_amount ?? row.allocated_amount)}</td><td className="table-cell text-amber-700">{money(row.used_amount)}</td><td className="table-cell font-bold text-green-700">{money(row.remaining_amount)}</td><td className="table-cell">{row.currency}</td><td className="table-cell"><span className="rounded-full bg-green-50 px-2 py-1 text-xs font-semibold text-green-700">{row.status}</span></td><td className="table-cell">{hasPermission('fuel.budgets.manage') && <button className="rounded-lg p-2 text-blue-600 hover:bg-blue-50" onClick={() => edit(row)}><Pencil size={17}/></button>}</td></tr>)}</tbody></table></div>}</div>
    <Modal open={Boolean(form)} onClose={() => setForm(null)} title={form?.id ? 'កែថវិកាសាំង' : 'កំណត់ថវិកាសាំង'} size="max-w-3xl"><form className="space-y-5" onSubmit={save}>
      <Section number="1" title="រយៈពេលថវិកា" description="កំណត់ថ្ងៃ/ខែសម្រាប់ Top Up ថវិកាសាំង។"><Field label="ថ្ងៃខែថវិកា *"><input required type="date" className="field" value={form?.budget_date || ''} onChange={event => setForm({ ...form, budget_date: event.target.value })}/></Field></Section>
      <Section number="2" title="វិសាលភាពថវិកា" description="បើអត់មាន Plan សូមជ្រើសតាមខេត្ត។ បើមាន Plan អាចភ្ជាប់សម្រាប់តាមដានលម្អិត។"><div className="grid gap-4 md:grid-cols-2"><Field label="ប្រភេទវិសាលភាព *"><select required className="field" value={form?.budget_scope || 'province'} onChange={event => selectScope(event.target.value)}><option value="province">តាមខេត្ត / អត់មាន Plan</option><option value="plan">តាមផែនការចុះ</option></select></Field><Field label="Sales *"><select required className="field" value={form?.sales_user_id || ''} onChange={event => selectSales(event.target.value)}><option value="">ជ្រើសរើស Sales</option>{lookups.sales.map(item => <option key={item.id} value={item.id}>{item.full_name}</option>)}</select></Field><Field label="ខេត្ត *"><select required className="field" value={form?.province_id || ''} onChange={event => setForm({ ...form, province_id: event.target.value })}><option value="">ជ្រើសរើសខេត្ត</option>{lookups.provinces.map(item => <option key={item.id} value={item.id}>{item.name_kh}</option>)}</select></Field>{form?.budget_scope === 'plan' && <Field label="ផែនការចុះ *"><select required disabled={!form?.sales_user_id} className="field disabled:bg-slate-100" value={form?.visit_plan_id || ''} onChange={event => selectPlan(event.target.value)}><option value="">{form?.sales_user_id ? 'ជ្រើសរើស Plan' : 'សូមជ្រើស Sales ជាមុន'}</option>{planOptions.map(plan => <option key={plan.id} value={plan.id}>{plan.title} · {plan.province}{plan.district ? `, ${plan.district}` : ''} · {formatDate(plan.start_date)} - {formatDate(plan.end_date)}</option>)}</select><p className="mt-1 text-xs text-slate-500">រកឃើញ {planOptions.length} ផែនការរបស់ Sales នេះ</p></Field>}</div></Section>
      <Section number="3" title="ចំនួន និងលក្ខខណ្ឌ" description="បញ្ចូលចំនួនថវិកា រូបិយប័ណ្ណ និងកំណត់សម្គាល់។"><div className="grid gap-4 md:grid-cols-2"><Field label="ចំនួនថវិកា *"><input required min="0.01" step="0.01" type="number" className="field" value={form?.allocated_amount || ''} onChange={event => setForm({ ...form, allocated_amount: event.target.value })}/></Field><Field label="រូបិយប័ណ្ណ"><select className="field" value={form?.currency || 'KHR'} onChange={event => setForm({ ...form, currency: event.target.value })}><option>KHR</option><option>USD</option></select></Field><div className="md:col-span-2"><Field label="កំណត់សម្គាល់"><textarea rows="2" className="field" value={form?.note || ''} onChange={event => setForm({ ...form, note: event.target.value })}/></Field></div></div></Section>
      <div className="flex justify-end gap-2 border-t pt-4"><button type="button" className="btn-secondary" onClick={() => setForm(null)}>បោះបង់</button><button className="btn-primary">រក្សាទុកថវិកា</button></div>
    </form></Modal>
  </div>
}
function Field({ label, children }) { return <div><label className="label">{label}</label>{children}</div> }
function Section({ number, title, description, children }) { return <section className="rounded-2xl border p-4"><div className="mb-4 flex gap-3"><span className="grid size-8 place-items-center rounded-full bg-blue-600 text-sm font-bold text-white">{number}</span><div><h3 className="font-bold">{title}</h3><p className="text-xs text-slate-500">{description}</p></div></div>{children}</section> }
function Summary({ icon: Icon, label, value }) { return <div className="card flex items-center gap-3 p-4"><span className="grid size-11 place-items-center rounded-xl bg-blue-50 text-blue-600"><Icon size={21}/></span><div><p className="text-xs text-slate-500">{label}</p><p className="text-xl font-bold">{value}</p></div></div> }
function normalizeLocation(value = '') { return value.trim().toLowerCase().replace(/^(ខេត្ត|រាជធានី)/, '').replace(/\s+/g, '') }
function formatDate(value) { return value ? new Date(`${value}T00:00:00`).toLocaleDateString('km-KH') : '' }
function compareBudgetOrder(left, right) {
  const leftDate = new Date(left.created_at || 0).getTime()
  const rightDate = new Date(right.created_at || 0).getTime()
  return (Number(left.fiscal_year) || 0) - (Number(right.fiscal_year) || 0)
    || new Date(left.budget_date || 0).getTime() - new Date(right.budget_date || 0).getTime()
    || (Number(left.fiscal_month || 0) - Number(right.fiscal_month || 0))
    || (Number(left.fiscal_week || 0) - Number(right.fiscal_week || 0))
    || leftDate - rightDate
}
