import { useEffect, useState } from 'react'
import { Bell, Building2, Save, ShieldCheck } from 'lucide-react'
import { toast } from 'sonner'
import { supabase } from '../services/supabase'
import { sanitizeText } from '../utils/formatters'
import LoadingState from '../components/common/LoadingState'

const empty={company_name:'',company_logo:'',company_phone:'',company_address:'',reminder_minutes:30}
export default function SettingsPage(){const[form,setForm]=useState(empty),[id,setId]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);useEffect(()=>{supabase.from('settings').select('*').limit(1).maybeSingle().then(({data})=>{if(data){setId(data.id);setForm(data)}setLoading(false)})},[]);const save=async e=>{e.preventDefault();setBusy(true);const payload={...form,company_name:sanitizeText(form.company_name),company_address:sanitizeText(form.company_address),reminder_minutes:Number(form.reminder_minutes)};const{data,error}=id?await supabase.from('settings').update(payload).eq('id',id).select().single():await supabase.from('settings').insert(payload).select().single();setBusy(false);if(error)toast.error(error.message);else{setId(data.id);toast.success('បានរក្សាទុកការកំណត់')}};const update=e=>setForm({...form,[e.target.name]:e.target.value});if(loading)return <LoadingState/>;return <div className="space-y-5"><div><h1 className="text-2xl font-bold">ការកំណត់</h1><p className="mt-1 text-sm text-slate-500">កំណត់ព័ត៌មានក្រុមហ៊ុន និង Notification</p></div><form onSubmit={save} className="grid gap-5 xl:grid-cols-3"><section className="card p-5 xl:col-span-2"><h2 className="mb-5 flex items-center gap-2 font-bold"><Building2 size={19} className="text-blue-600"/>ព័ត៌មានក្រុមហ៊ុន</h2><div className="grid gap-4 md:grid-cols-2"><div><label className="label">ឈ្មោះក្រុមហ៊ុន</label><input className="field" required name="company_name" value={form.company_name||''} onChange={update}/></div><div><label className="label">Logo URL</label><input className="field" type="url" name="company_logo" value={form.company_logo||''} onChange={update}/></div><div><label className="label">លេខទូរស័ព្ទ</label><input className="field" name="company_phone" value={form.company_phone||''} onChange={update}/></div><div><label className="label">រំលឹកមុន (នាទី)</label><input className="field" min="0" type="number" name="reminder_minutes" value={form.reminder_minutes} onChange={update}/></div><div className="md:col-span-2"><label className="label">អាសយដ្ឋាន</label><textarea className="field min-h-24" name="company_address" value={form.company_address||''} onChange={update}/></div></div><button className="btn-primary mt-5" disabled={busy}><Save size={17}/>{busy?'កំពុងរក្សា...':'រក្សាទុក'}</button></section><aside className="space-y-5"><div className="card p-5"><Bell className="text-blue-600"/><h3 className="mt-3 font-bold">Notification Settings</h3><p className="mt-2 text-sm text-slate-500">Browser notifications ប្រើ permission របស់ browser ហើយ status រក្សានៅ Supabase ដើម្បីមិនផ្ញើស្ទួន។</p></div><div className="card p-5"><ShieldCheck className="text-green-600"/><h3 className="mt-3 font-bold">User Management</h3><p className="mt-2 text-sm text-slate-500">បង្កើត Auth users ក្នុង Supabase Dashboard។ Profile នឹងបង្កើតស្វ័យប្រវត្តិ ហើយ Admin អាចកែ role ក្នុង profiles table។</p></div></aside></form></div>}
