export const PERMISSIONS = [
  { key: 'dashboard', label: 'ផ្ទាំងគ្រប់គ្រង', group: 'ទូទៅ' },
  { key: 'notifications', label: 'ការជូនដំណឹង', group: 'ទូទៅ' },
  { key: 'customers', label: 'គ្រប់គ្រងអតិថិជន', group: 'ការងារលក់' },
  { key: 'follow_ups', label: 'Follow Up', group: 'ការងារលក់' },
  { key: 'visit_plans', label: 'ផែនការចុះស្រុក', group: 'ការងារលក់' },
  { key: 'calls', label: 'ប្រវត្តិការហៅ', group: 'ការងារលក់' },
  { key: 'reports', label: 'របាយការណ៍', group: 'ការគ្រប់គ្រង' },
  { key: 'sales_team', label: 'មើលក្រុមលក់', group: 'ការគ្រប់គ្រង' },
  { key: 'markets.view', label: 'មើលព័ត៌មានផ្សារ', group: 'គ្រប់គ្រងផ្សារ' },
  { key: 'markets.create', label: 'បង្កើតផ្សារ', group: 'គ្រប់គ្រងផ្សារ' },
  { key: 'markets.update', label: 'កែប្រែផ្សារ និងតូប', group: 'គ្រប់គ្រងផ្សារ' },
  { key: 'markets.delete', label: 'លុបផ្សារ', group: 'គ្រប់គ្រងផ្សារ' },
  { key: 'markets.restore', label: 'Restore ផ្សារ', group: 'គ្រប់គ្រងផ្សារ' },
  { key: 'markets.import', label: 'Import ទិន្នន័យផ្សារ', group: 'គ្រប់គ្រងផ្សារ' },
  { key: 'markets.export', label: 'Export ទិន្នន័យផ្សារ', group: 'គ្រប់គ្រងផ្សារ' },
  { key: 'markets.view_audit', label: 'មើល Audit Log ផ្សារ', group: 'គ្រប់គ្រងផ្សារ' },
  { key: 'expenses.view', label: 'មើលសំណើចំណាយ', group: 'គ្រប់គ្រងចំណាយ' },
  { key: 'expenses.create', label: 'បង្កើតសំណើចំណាយ', group: 'គ្រប់គ្រងចំណាយ' },
  { key: 'expenses.submit', label: 'ដាក់ស្នើចំណាយ', group: 'គ្រប់គ្រងចំណាយ' },
  { key: 'expenses.approve', label: 'អនុម័ត/បដិសេធសំណើ', group: 'គ្រប់គ្រងចំណាយ' },
  { key: 'expenses.pay', label: 'កត់ត្រាការទូទាត់', group: 'គ្រប់គ្រងចំណាយ' },
  { key: 'expenses.actual', label: 'កត់ត្រាចំណាយជាក់ស្តែង', group: 'គ្រប់គ្រងចំណាយ' },
  { key: 'expenses.complete', label: 'ផ្ទៀងផ្ទាត់ និងបិទបញ្ជី', group: 'គ្រប់គ្រងចំណាយ' },
  { key: 'expenses.reopen', label: 'បើកបញ្ជីឡើងវិញ', group: 'គ្រប់គ្រងចំណាយ' },
  { key: 'expenses.override_limit', label: 'អនុញ្ញាតចំណាយលើសកម្រិត', group: 'គ្រប់គ្រងចំណាយ' },
  { key: 'expenses.audit', label: 'មើល Audit Log ចំណាយ', group: 'គ្រប់គ្រងចំណាយ' },
  { key: 'expenses.reports', label: 'របាយការណ៍ចំណាយ', group: 'គ្រប់គ្រងចំណាយ' },
  { key: 'expenses.budgets.view', label: 'មើលថវិកាខេត្ត', group: 'គ្រប់គ្រងចំណាយ' },
  { key: 'expenses.budgets.manage', label: 'គ្រប់គ្រងថវិកាខេត្ត', group: 'គ្រប់គ្រងចំណាយ' },
  { key: 'expenses.budgets.revise', label: 'កែសម្រួលថវិកា', group: 'គ្រប់គ្រងចំណាយ' },
  { key: 'expenses.fiscal_lock', label: 'បិទ/បើកឆ្នាំថវិកា', group: 'គ្រប់គ្រងចំណាយ' },
  { key: 'expenses.verify', label: 'ផ្ទៀងផ្ទាត់បញ្ជីចំណាយ', group: 'គ្រប់គ្រងចំណាយ' },
  { key: 'fuel.view', label: 'មើលចំណាយសាំង', group: 'ចំណាយសាំង' },
  { key: 'fuel.create', label: 'កត់ត្រាចំណាយសាំង', group: 'ចំណាយសាំង' },
  { key: 'fuel.submit', label: 'ដាក់ស្នើចំណាយសាំង', group: 'ចំណាយសាំង' },
  { key: 'fuel.approve', label: 'អនុម័តចំណាយសាំង', group: 'ចំណាយសាំង' },
  { key: 'fuel.reports', label: 'របាយការណ៍ចំណាយសាំង', group: 'ចំណាយសាំង' },
  { key: 'vehicles.manage', label: 'គ្រប់គ្រងយានយន្ត', group: 'ចំណាយសាំង' },
  { key: 'fuel.budgets.view', label: 'មើលថវិកាសាំង', group: 'ចំណាយសាំង' },
  { key: 'fuel.budgets.manage', label: 'កំណត់ថវិកាសាំង', group: 'ចំណាយសាំង' },
  { key: 'settings', label: 'ការកំណត់', group: 'ប្រព័ន្ធ' },
  { key: 'user_management', label: 'គ្រប់គ្រងអ្នកប្រើប្រាស់', group: 'ប្រព័ន្ធ' },
]

export const ROLE_DEFAULTS = {
  admin: PERMISSIONS.map(item => item.key),
  manager: ['dashboard', 'customers', 'follow_ups', 'visit_plans', 'calls', 'reports', 'sales_team', 'markets.view', 'markets.create', 'markets.update', 'markets.import', 'markets.export', 'notifications'],
  sales: ['dashboard', 'customers', 'follow_ups', 'visit_plans', 'calls', 'notifications'],
  user: ['dashboard', 'notifications'],
}
