-- Market Management module: lookup data, markets, auditing, storage and RLS.

create sequence if not exists public.market_code_sequence start 1;

create table public.provinces (
  id bigint generated by default as identity primary key,
  code text not null unique check (code ~ '^[A-Z0-9]{2,10}$'),
  name_kh text not null,
  name_en text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.districts (
  id bigint generated by default as identity primary key,
  province_id bigint not null references public.provinces(id) on delete restrict,
  code text not null unique,
  name_kh text not null,
  name_en text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.communes (
  id bigint generated by default as identity primary key,
  district_id bigint not null references public.districts(id) on delete restrict,
  code text not null unique,
  name_kh text not null,
  name_en text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.villages (
  id bigint generated by default as identity primary key,
  commune_id bigint not null references public.communes(id) on delete restrict,
  code text not null unique,
  name_kh text not null,
  name_en text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.market_types (
  id bigint generated by default as identity primary key,
  code text not null unique check (code ~ '^[a-z][a-z0-9_]{2,39}$'),
  name_kh text not null,
  name_en text not null unique,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.markets (
  id uuid primary key default gen_random_uuid(),
  market_code text not null unique,
  name_kh text not null check (char_length(trim(name_kh)) between 2 and 200),
  name_en text check (name_en is null or char_length(trim(name_en)) between 2 and 200),
  market_type_id bigint not null references public.market_types(id) on delete restrict,
  status text not null default 'active' check (status in ('active','inactive','under_construction','closed')),
  opening_date date,
  province_id bigint not null references public.provinces(id) on delete restrict,
  district_id bigint not null references public.districts(id) on delete restrict,
  commune_id bigint not null references public.communes(id) on delete restrict,
  village_id bigint references public.villages(id) on delete restrict,
  street text,
  full_address text,
  latitude numeric(10,7) not null check (latitude between -90 and 90),
  longitude numeric(10,7) not null check (longitude between -180 and 180),
  google_map_url text,
  manager_name text,
  phone text check (phone is null or phone ~ '^(\\+?855|0)[1-9][0-9]{7,8}$'),
  email text check (email is null or email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}$'),
  opening_time time,
  closing_time time,
  total_stalls integer not null default 0 check (total_stalls >= 0),
  occupied_stalls integer not null default 0 check (occupied_stalls >= 0 and occupied_stalls <= total_stalls),
  trader_count integer not null default 0 check (trader_count >= 0),
  market_size numeric(12,2) check (market_size is null or market_size >= 0),
  description text,
  image text,
  created_by uuid not null references public.profiles(id) on delete restrict default auth.uid(),
  updated_by uuid references public.profiles(id) on delete set null,
  deleted_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  check (closing_time is null or opening_time is null or closing_time > opening_time)
);

create table public.market_audit_logs (
  id uuid primary key default gen_random_uuid(),
  market_id uuid not null,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null check (action in ('created','updated','deleted','restored')),
  old_values jsonb,
  new_values jsonb,
  created_at timestamptz not null default now()
);

create index districts_province_idx on public.districts(province_id, is_active);
create index communes_district_idx on public.communes(district_id, is_active);
create index villages_commune_idx on public.villages(commune_id, is_active);
create index markets_name_kh_idx on public.markets(name_kh);
create index markets_name_en_idx on public.markets(name_en);
create index markets_type_idx on public.markets(market_type_id);
create index markets_status_idx on public.markets(status);
create index markets_location_idx on public.markets(province_id, district_id, commune_id);
create index markets_created_idx on public.markets(created_at desc);
create index markets_deleted_idx on public.markets(deleted_at) where deleted_at is not null;
create index market_audit_market_idx on public.market_audit_logs(market_id, created_at desc);

create or replace function public.prepare_market() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  province_code text;
  district_province_id bigint;
  commune_district_id bigint;
  village_commune_id bigint;
begin
  select code into province_code from public.provinces where id = new.province_id and is_active;
  select province_id into district_province_id from public.districts where id = new.district_id and is_active;
  select district_id into commune_district_id from public.communes where id = new.commune_id and is_active;
  if province_code is null or district_province_id is distinct from new.province_id or commune_district_id is distinct from new.district_id then
    raise exception 'Invalid province, district or commune relationship';
  end if;
  if new.village_id is not null then
    select commune_id into village_commune_id from public.villages where id = new.village_id and is_active;
    if village_commune_id is distinct from new.commune_id then raise exception 'Invalid village relationship'; end if;
  end if;
  if tg_op = 'INSERT' then
    new.market_code := 'MKT-' || province_code || '-' || to_char(current_date, 'YYYY') || '-' || lpad(nextval('public.market_code_sequence')::text, 5, '0');
    new.created_by := auth.uid();
  else
    new.market_code := old.market_code;
    new.updated_by := auth.uid();
  end if;
  new.google_map_url := 'https://www.google.com/maps?q=' || new.latitude || ',' || new.longitude;
  return new;
end $$;

create trigger markets_prepare before insert or update on public.markets
for each row execute function public.prepare_market();
create trigger provinces_updated_at before update on public.provinces for each row execute function public.set_updated_at();
create trigger districts_updated_at before update on public.districts for each row execute function public.set_updated_at();
create trigger communes_updated_at before update on public.communes for each row execute function public.set_updated_at();
create trigger villages_updated_at before update on public.villages for each row execute function public.set_updated_at();
create trigger market_types_updated_at before update on public.market_types for each row execute function public.set_updated_at();
create trigger markets_updated_at before update on public.markets for each row execute function public.set_updated_at();

create or replace function public.audit_market_change() returns trigger
language plpgsql security definer set search_path = public as $$
declare action_name text;
begin
  action_name := case
    when tg_op = 'INSERT' then 'created'
    when old.deleted_at is null and new.deleted_at is not null then 'deleted'
    when old.deleted_at is not null and new.deleted_at is null then 'restored'
    else 'updated'
  end;
  insert into public.market_audit_logs(market_id, actor_id, action, old_values, new_values)
  values(coalesce(new.id, old.id), auth.uid(), action_name,
    case when tg_op = 'INSERT' then null else to_jsonb(old) end,
    case when tg_op = 'DELETE' then null else to_jsonb(new) end);
  return new;
end $$;

create trigger markets_audit after insert or update on public.markets
for each row execute function public.audit_market_change();

create or replace function public.market_statistics() returns jsonb
language sql stable security invoker set search_path = public as $$
  select jsonb_build_object(
    'total', count(*),
    'active', count(*) filter (where status = 'active'),
    'inactive', count(*) filter (where status = 'inactive'),
    'under_construction', count(*) filter (where status = 'under_construction'),
    'closed', count(*) filter (where status = 'closed'),
    'public_markets', count(*) filter (where market_type_id = (select id from public.market_types where code = 'public_market')),
    'total_stalls', coalesce(sum(total_stalls), 0),
    'occupied_stalls', coalesce(sum(occupied_stalls), 0),
    'trader_count', coalesce(sum(trader_count), 0)
  ) from public.markets where deleted_at is null;
$$;

alter table public.provinces enable row level security;
alter table public.districts enable row level security;
alter table public.communes enable row level security;
alter table public.villages enable row level security;
alter table public.market_types enable row level security;
alter table public.markets enable row level security;
alter table public.market_audit_logs enable row level security;

create policy provinces_read on public.provinces for select to authenticated using (true);
create policy districts_read on public.districts for select to authenticated using (true);
create policy communes_read on public.communes for select to authenticated using (true);
create policy villages_read on public.villages for select to authenticated using (true);
create policy market_types_read on public.market_types for select to authenticated using (true);
create policy provinces_admin_write on public.provinces for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy districts_admin_write on public.districts for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy communes_admin_write on public.communes for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy villages_admin_write on public.villages for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy market_types_admin_write on public.market_types for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy markets_permission_select on public.markets for select to authenticated using (public.has_permission('markets'));
create policy markets_permission_insert on public.markets for insert to authenticated with check (public.has_permission('markets') and created_by = auth.uid());
create policy markets_permission_update on public.markets for update to authenticated using (public.has_permission('markets')) with check (public.has_permission('markets'));
create policy market_audit_permission_select on public.market_audit_logs for select to authenticated using (public.has_permission('markets'));

insert into public.market_types(code, name_kh, name_en) values
  ('public_market', 'ផ្សារសាធារណៈ', 'Public Market'),
  ('private_market', 'ផ្សារឯកជន', 'Private Market'),
  ('community_market', 'ផ្សារសហគមន៍', 'Community Market'),
  ('wholesale_market', 'ផ្សារបោះដុំ', 'Wholesale Market'),
  ('retail_market', 'ផ្សារលក់រាយ', 'Retail Market'),
  ('border_market', 'ផ្សារព្រំដែន', 'Border Market'),
  ('night_market', 'ផ្សាររាត្រី', 'Night Market')
on conflict (code) do update set name_kh = excluded.name_kh, name_en = excluded.name_en;

update public.app_roles
set permissions = permissions || '["markets"]'::jsonb
where key in ('admin', 'manager') and not permissions ? 'markets';

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values('market-images', 'market-images', true, 5242880, array['image/jpeg','image/png','image/webp'])
on conflict (id) do nothing;

create policy market_images_read on storage.objects for select to authenticated using (bucket_id = 'market-images');
create policy market_images_insert on storage.objects for insert to authenticated with check (bucket_id = 'market-images' and public.has_permission('markets'));
create policy market_images_update on storage.objects for update to authenticated using (bucket_id = 'market-images' and public.has_permission('markets')) with check (bucket_id = 'market-images' and public.has_permission('markets'));
create policy market_images_delete on storage.objects for delete to authenticated using (bucket_id = 'market-images' and public.has_permission('markets'));

grant execute on function public.market_statistics() to authenticated;
