-- Provincial Expense Management: budgets, approvals, payments, actuals and closure.

create sequence if not exists public.expense_request_code_sequence start 1;
create sequence if not exists public.expense_payment_code_sequence start 1;

create table public.projects (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name_kh text not null,
  name_en text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.expense_categories (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name_kh text not null,
  name_en text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.approval_rules (
  id bigint generated by default as identity primary key,
  name text not null,
  min_amount numeric(16,2) not null default 0 check (min_amount >= 0),
  max_amount numeric(16,2) check (max_amount is null or max_amount >= min_amount),
  approval_level integer not null check (approval_level > 0),
  approver_role text not null references public.app_roles(key) on update cascade,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(min_amount, max_amount, approval_level)
);

create table public.provincial_budgets (
  id uuid primary key default gen_random_uuid(),
  fiscal_year integer not null check (fiscal_year between 2000 and 2200),
  province_id bigint not null references public.provinces(id) on delete restrict,
  project_id bigint not null references public.projects(id) on delete restrict,
  expense_category_id bigint not null references public.expense_categories(id) on delete restrict,
  approved_amount numeric(16,2) not null check (approved_amount >= 0),
  revised_amount numeric(16,2) not null default 0,
  committed_amount numeric(16,2) not null default 0 check (committed_amount >= 0),
  actual_expense_amount numeric(16,2) not null default 0 check (actual_expense_amount >= 0),
  remaining_amount numeric(16,2) generated always as (approved_amount + revised_amount - committed_amount - actual_expense_amount) stored,
  status text not null default 'active' check (status in ('draft','active','closed','cancelled')),
  created_by uuid not null references public.profiles(id) on delete restrict default auth.uid(),
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(fiscal_year, province_id, project_id, expense_category_id),
  check (approved_amount + revised_amount >= 0)
);

create table public.expense_requests (
  id uuid primary key default gen_random_uuid(),
  request_code text not null unique,
  request_date date not null default current_date,
  province_id bigint not null references public.provinces(id) on delete restrict,
  project_id bigint not null references public.projects(id) on delete restrict,
  expense_category_id bigint not null references public.expense_categories(id) on delete restrict,
  purpose text not null check (char_length(trim(purpose)) between 5 and 2000),
  requested_amount numeric(16,2) not null check (requested_amount > 0),
  approved_amount numeric(16,2) not null default 0 check (approved_amount >= 0),
  amount_received numeric(16,2) not null default 0 check (amount_received >= 0),
  actual_amount numeric(16,2) not null default 0 check (actual_amount >= 0),
  returned_amount numeric(16,2) not null default 0 check (returned_amount >= 0),
  status text not null default 'draft' check (status in ('draft','submitted','under_review','returned','approved','rejected','payment_processing','paid','completed','cancelled')),
  requested_by uuid not null references public.profiles(id) on delete restrict default auth.uid(),
  submitted_at timestamptz,
  approved_at timestamptz,
  paid_at timestamptz,
  completed_at timestamptz,
  created_by uuid not null references public.profiles(id) on delete restrict default auth.uid(),
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table public.expense_approvals (
  id uuid primary key default gen_random_uuid(),
  expense_request_id uuid not null references public.expense_requests(id) on delete cascade,
  approval_level integer not null check (approval_level > 0),
  approver_role text not null references public.app_roles(key) on update cascade,
  approver_id uuid references public.profiles(id) on delete set null,
  decision text not null default 'pending' check (decision in ('pending','approved','rejected','returned')),
  comment text,
  action_date timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(expense_request_id, approval_level)
);

create table public.expense_items (
  id uuid primary key default gen_random_uuid(),
  expense_request_id uuid not null references public.expense_requests(id) on delete cascade,
  expense_date date not null,
  description text not null check (char_length(trim(description)) >= 3),
  vendor_name text not null,
  invoice_number text not null,
  quantity numeric(12,2) not null default 1 check (quantity > 0),
  unit_price numeric(16,2) not null check (unit_price >= 0),
  amount numeric(16,2) generated always as (quantity * unit_price) stored,
  attachment text not null,
  created_by uuid references public.profiles(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(expense_request_id, invoice_number)
);

create table public.expense_payments (
  id uuid primary key default gen_random_uuid(),
  expense_request_id uuid not null references public.expense_requests(id) on delete cascade,
  payment_code text not null unique,
  payment_date date not null default current_date,
  payment_method text not null check (payment_method in ('cash','bank_transfer','cheque','advance_payment','reimbursement')),
  amount numeric(16,2) not null check (amount > 0),
  bank_name text,
  transaction_reference text,
  recipient_name text not null,
  paid_by uuid not null references public.profiles(id) on delete restrict default auth.uid(),
  attachment text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.expense_documents (
  id uuid primary key default gen_random_uuid(),
  expense_request_id uuid not null references public.expense_requests(id) on delete cascade,
  document_type text not null check (document_type in ('invoice','receipt','mission_letter','participant_list','activity_photo','completion_report','payment_proof','other')),
  file_name text not null,
  file_path text not null,
  uploaded_by uuid references public.profiles(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.expense_audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  module text not null,
  record_id uuid,
  old_values jsonb,
  new_values jsonb,
  ip_address inet,
  created_at timestamptz not null default now()
);

create index provincial_budgets_filter_idx on public.provincial_budgets(fiscal_year, province_id, project_id, expense_category_id, status);
create index expense_requests_filter_idx on public.expense_requests(province_id, project_id, expense_category_id, status, request_date desc) where deleted_at is null;
create index expense_requests_requester_idx on public.expense_requests(requested_by, status, created_at desc);
create index expense_approvals_pending_idx on public.expense_approvals(approver_role, decision, approval_level);
create index expense_items_request_idx on public.expense_items(expense_request_id, expense_date);
create index expense_payments_request_idx on public.expense_payments(expense_request_id, payment_date);
create index expense_documents_request_idx on public.expense_documents(expense_request_id, document_type);
create index expense_audit_record_idx on public.expense_audit_logs(module, record_id, created_at desc);

create trigger projects_updated_at before update on public.projects for each row execute function public.set_updated_at();
create trigger expense_categories_updated_at before update on public.expense_categories for each row execute function public.set_updated_at();
create trigger approval_rules_updated_at before update on public.approval_rules for each row execute function public.set_updated_at();
create trigger provincial_budgets_updated_at before update on public.provincial_budgets for each row execute function public.set_updated_at();
create trigger expense_requests_updated_at before update on public.expense_requests for each row execute function public.set_updated_at();
create trigger expense_approvals_updated_at before update on public.expense_approvals for each row execute function public.set_updated_at();
create trigger expense_items_updated_at before update on public.expense_items for each row execute function public.set_updated_at();
create trigger expense_payments_updated_at before update on public.expense_payments for each row execute function public.set_updated_at();
create trigger expense_documents_updated_at before update on public.expense_documents for each row execute function public.set_updated_at();

create or replace function public.prepare_expense_request() returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    new.request_code := 'EXP-' || extract(year from new.request_date)::integer || '-' || lpad(nextval('public.expense_request_code_sequence')::text, 6, '0');
    new.requested_by := auth.uid(); new.created_by := auth.uid();
  else
    new.request_code := old.request_code; new.requested_by := old.requested_by; new.updated_by := auth.uid();
    if old.status = 'completed' and not public.has_permission('expenses.reopen') then raise exception 'Completed expense is locked'; end if;
    if old.status not in ('draft','returned') and row(new.request_date,new.province_id,new.project_id,new.expense_category_id,new.purpose,new.requested_amount)
      is distinct from row(old.request_date,old.province_id,old.project_id,old.expense_category_id,old.purpose,old.requested_amount) then
      raise exception 'Only draft or returned requests can be edited';
    end if;
  end if;
  return new;
end $$;
create trigger expense_requests_prepare before insert or update on public.expense_requests for each row execute function public.prepare_expense_request();

create or replace function public.expense_scope_allows(p_province_id bigint) returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.profiles where id = auth.uid() and is_active and (role = 'admin' or province_id is null or province_id = p_province_id));
$$;

create or replace function public.available_budget(p_province_id bigint, p_project_id bigint, p_category_id bigint, p_fiscal_year integer)
returns numeric language sql stable security definer set search_path = public as $$
  select coalesce((select remaining_amount from public.provincial_budgets
    where province_id=p_province_id and project_id=p_project_id and expense_category_id=p_category_id
      and fiscal_year=p_fiscal_year and status='active'),0);
$$;

create or replace function public.submit_expense_request(p_request_id uuid) returns public.expense_requests
language plpgsql security definer set search_path = public as $$
declare request_row public.expense_requests; budget_row public.provincial_budgets; result public.expense_requests; rule_count integer;
begin
  if not public.has_permission('expenses.submit') then raise exception 'Access denied'; end if;
  select * into request_row from public.expense_requests where id=p_request_id and deleted_at is null for update;
  if request_row.requested_by <> auth.uid() or request_row.status not in ('draft','returned') then raise exception 'Request cannot be submitted'; end if;
  select * into budget_row from public.provincial_budgets where fiscal_year=extract(year from request_row.request_date)::integer
    and province_id=request_row.province_id and project_id=request_row.project_id and expense_category_id=request_row.expense_category_id and status='active' for update;
  if budget_row.id is null then raise exception 'No active budget found'; end if;
  if request_row.requested_amount > budget_row.remaining_amount then
    raise exception 'Budget exceeded. Available: %, Requested: %, Exceeded: %', budget_row.remaining_amount, request_row.requested_amount, request_row.requested_amount-budget_row.remaining_amount;
  end if;
  delete from public.expense_approvals where expense_request_id=p_request_id;
  insert into public.expense_approvals(expense_request_id,approval_level,approver_role)
  select p_request_id,approval_level,approver_role from public.approval_rules
  where is_active and request_row.requested_amount >= min_amount and (max_amount is null or request_row.requested_amount <= max_amount)
  order by approval_level;
  get diagnostics rule_count = row_count;
  if rule_count=0 then raise exception 'No approval rule configured for this amount'; end if;
  update public.expense_requests set status='submitted',submitted_at=now(),updated_by=auth.uid() where id=p_request_id returning * into result;
  return result;
end $$;

create or replace function public.decide_expense_request(p_request_id uuid,p_decision text,p_comment text default null,p_approved_amount numeric default null)
returns public.expense_requests language plpgsql security definer set search_path = public as $$
declare request_row public.expense_requests; approval_row public.expense_approvals; result public.expense_requests; pending_count integer; actor_role text;
begin
  if not public.has_permission('expenses.approve') then raise exception 'Access denied'; end if;
  if p_decision not in ('approved','rejected','returned') then raise exception 'Invalid decision'; end if;
  select role into actor_role from public.profiles where id=auth.uid();
  select * into request_row from public.expense_requests where id=p_request_id and deleted_at is null for update;
  if request_row.requested_by=auth.uid() then raise exception 'Requester cannot approve own request'; end if;
  select * into approval_row from public.expense_approvals where expense_request_id=p_request_id and decision='pending'
    order by approval_level limit 1 for update;
  if approval_row.id is null then raise exception 'No pending approval'; end if;
  if actor_role<>'admin' and approval_row.approver_role<>actor_role then raise exception 'This approval level requires role %',approval_row.approver_role; end if;
  if p_decision in ('rejected','returned') and char_length(trim(coalesce(p_comment,'')))<3 then raise exception 'Comment is required'; end if;
  update public.expense_approvals set decision=p_decision,comment=nullif(trim(p_comment),''),approver_id=auth.uid(),action_date=now() where id=approval_row.id;
  if p_decision='rejected' then update public.expense_requests set status='rejected',updated_by=auth.uid() where id=p_request_id returning * into result; return result; end if;
  if p_decision='returned' then update public.expense_requests set status='returned',updated_by=auth.uid() where id=p_request_id returning * into result; return result; end if;
  select count(*) into pending_count from public.expense_approvals where expense_request_id=p_request_id and decision='pending';
  if pending_count>0 then update public.expense_requests set status='under_review',updated_by=auth.uid() where id=p_request_id returning * into result;
  else
    result.approved_amount := least(coalesce(p_approved_amount,request_row.requested_amount),request_row.requested_amount);
    update public.provincial_budgets set committed_amount=committed_amount+result.approved_amount,updated_by=auth.uid()
      where fiscal_year=extract(year from request_row.request_date)::integer and province_id=request_row.province_id and project_id=request_row.project_id and expense_category_id=request_row.expense_category_id;
    update public.expense_requests set status='approved',approved_amount=result.approved_amount,approved_at=now(),updated_by=auth.uid() where id=p_request_id returning * into result;
  end if;
  return result;
end $$;

create or replace function public.create_expense_payment(p_request_id uuid,p_payment_date date,p_method text,p_amount numeric,p_bank_name text,p_reference text,p_recipient text,p_attachment text)
returns public.expense_payments language plpgsql security definer set search_path = public as $$
declare request_row public.expense_requests; paid_total numeric; payment public.expense_payments;
begin
  if not public.has_permission('expenses.pay') then raise exception 'Access denied'; end if;
  select * into request_row from public.expense_requests where id=p_request_id and status in ('approved','payment_processing','paid') for update;
  if request_row.id is null then raise exception 'Request is not approved for payment'; end if;
  select coalesce(sum(amount),0) into paid_total from public.expense_payments where expense_request_id=p_request_id;
  if p_amount<=0 or paid_total+p_amount>request_row.approved_amount then raise exception 'Payment exceeds unpaid balance %',request_row.approved_amount-paid_total; end if;
  insert into public.expense_payments(expense_request_id,payment_code,payment_date,payment_method,amount,bank_name,transaction_reference,recipient_name,paid_by,attachment)
  values(p_request_id,'PAY-'||extract(year from p_payment_date)::integer||'-'||lpad(nextval('public.expense_payment_code_sequence')::text,6,'0'),p_payment_date,p_method,p_amount,nullif(p_bank_name,''),nullif(p_reference,''),p_recipient,auth.uid(),p_attachment) returning * into payment;
  paid_total := paid_total+p_amount;
  update public.expense_requests set amount_received=paid_total,status=case when paid_total=approved_amount then 'paid' else 'payment_processing' end,
    paid_at=case when paid_total=approved_amount then now() else paid_at end,updated_by=auth.uid() where id=p_request_id;
  return payment;
end $$;

create or replace function public.sync_expense_actual() returns trigger language plpgsql security definer set search_path = public as $$
declare request_id uuid:=coalesce(new.expense_request_id,old.expense_request_id); total numeric;
begin
  select coalesce(sum(amount),0) into total from public.expense_items where expense_request_id=request_id;
  update public.expense_requests set actual_amount=total,returned_amount=greatest(amount_received-total,0),updated_by=auth.uid() where id=request_id and status<>'completed';
  return coalesce(new,old);
end $$;
create trigger expense_items_sync_actual after insert or update or delete on public.expense_items for each row execute function public.sync_expense_actual();

create or replace function public.complete_expense_request(p_request_id uuid) returns public.expense_requests
language plpgsql security definer set search_path = public as $$
declare request_row public.expense_requests; budget_row public.provincial_budgets; item_count integer; result public.expense_requests;
begin
  if not public.has_permission('expenses.complete') then raise exception 'Access denied'; end if;
  select * into request_row from public.expense_requests where id=p_request_id and status='paid' for update;
  if request_row.id is null then raise exception 'Only fully paid requests can be completed'; end if;
  select count(*) into item_count from public.expense_items where expense_request_id=p_request_id and attachment is not null;
  if item_count=0 then raise exception 'At least one supported expense item is required'; end if;
  if request_row.actual_amount>request_row.approved_amount and not public.has_permission('expenses.override_limit') then raise exception 'Actual expense exceeds approved amount'; end if;
  select * into budget_row from public.provincial_budgets where fiscal_year=extract(year from request_row.request_date)::integer and province_id=request_row.province_id and project_id=request_row.project_id and expense_category_id=request_row.expense_category_id for update;
  update public.provincial_budgets set committed_amount=greatest(committed_amount-request_row.approved_amount,0),actual_expense_amount=actual_expense_amount+request_row.actual_amount,updated_by=auth.uid() where id=budget_row.id;
  update public.expense_requests set status='completed',returned_amount=amount_received-actual_amount,completed_at=now(),updated_by=auth.uid() where id=p_request_id returning * into result;
  return result;
end $$;

create or replace function public.audit_expense_change() returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.expense_audit_logs(user_id,action,module,record_id,old_values,new_values)
  values(auth.uid(),lower(tg_op),tg_table_name,coalesce(new.id,old.id),case when tg_op='INSERT' then null else to_jsonb(old) end,case when tg_op='DELETE' then null else to_jsonb(new) end);
  return coalesce(new,old);
end $$;
create trigger expense_requests_audit after insert or update or delete on public.expense_requests for each row execute function public.audit_expense_change();
create trigger provincial_budgets_audit after insert or update or delete on public.provincial_budgets for each row execute function public.audit_expense_change();
create trigger expense_payments_audit after insert or update or delete on public.expense_payments for each row execute function public.audit_expense_change();

insert into public.app_roles(key,name,permissions,is_system) values
 ('expense_requester','Expense Requester','["expenses.view","expenses.create","expenses.submit","expenses.actual","notifications"]',true),
 ('provincial_approver','Provincial Approver','["expenses.view","expenses.approve","expenses.reports","notifications"]',true),
 ('finance_reviewer','Finance Reviewer','["expenses.view","expenses.approve","expenses.complete","expenses.reports","expenses.budgets.view","notifications"]',true),
 ('payment_officer','Payment Officer','["expenses.view","expenses.pay","expenses.reports","notifications"]',true),
 ('final_approver','Final Approver','["expenses.view","expenses.approve","expenses.reports","notifications"]',true),
 ('auditor','Auditor','["expenses.view","expenses.audit","expenses.reports","expenses.budgets.view"]',true)
on conflict(key) do update set name=excluded.name,permissions=excluded.permissions;

update public.app_roles set permissions=permissions||'["expenses.view","expenses.create","expenses.submit","expenses.approve","expenses.pay","expenses.actual","expenses.complete","expenses.reopen","expenses.override_limit","expenses.audit","expenses.reports","expenses.budgets.view","expenses.budgets.manage"]'::jsonb where key='admin';

insert into public.projects(code,name_kh,name_en) values
 ('ADMIN','រដ្ឋបាលទូទៅ','General Administration'),('LOCAL-DEV','អភិវឌ្ឍន៍មូលដ្ឋាន','Local Development'),('PUBLIC-SVC','សេវាសាធារណៈ','Public Services') on conflict(code) do nothing;
insert into public.expense_categories(code,name_kh,name_en) values
 ('TRAVEL','ចំណាយបេសកកម្ម','Travel and Mission'),('SUPPLIES','សម្ភារៈការិយាល័យ','Office Supplies'),('TRAINING','បណ្តុះបណ្តាល','Training'),('EVENT','កិច្ចប្រជុំ និងកម្មវិធី','Meetings and Events'),('MAINTENANCE','ថែទាំ និងជួសជុល','Maintenance'),('OTHER','ចំណាយផ្សេងៗ','Other') on conflict(code) do nothing;
insert into public.approval_rules(name,min_amount,max_amount,approval_level,approver_role) values
 ('Small - Provincial',0,499.99,1,'provincial_approver'),
 ('Medium - Provincial',500,5000,1,'provincial_approver'),('Medium - Finance',500,5000,2,'finance_reviewer'),
 ('Large - Provincial',5000.01,null,1,'provincial_approver'),('Large - Finance',5000.01,null,2,'finance_reviewer'),('Large - Final',5000.01,null,3,'final_approver')
on conflict do nothing;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('expense-documents','expense-documents',false,10485760,array['application/pdf','image/jpeg','image/png','image/webp']) on conflict(id) do nothing;

alter table public.projects enable row level security; alter table public.expense_categories enable row level security; alter table public.approval_rules enable row level security;
alter table public.provincial_budgets enable row level security; alter table public.expense_requests enable row level security; alter table public.expense_approvals enable row level security;
alter table public.expense_items enable row level security; alter table public.expense_payments enable row level security; alter table public.expense_documents enable row level security; alter table public.expense_audit_logs enable row level security;

create policy expense_lookups_read on public.projects for select to authenticated using(true);
create policy expense_categories_read on public.expense_categories for select to authenticated using(true);
create policy approval_rules_read on public.approval_rules for select to authenticated using(public.has_permission('expenses.view'));
create policy approval_rules_admin on public.approval_rules for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy budgets_read on public.provincial_budgets for select to authenticated using(public.has_permission('expenses.budgets.view') and public.expense_scope_allows(province_id));
create policy budgets_manage on public.provincial_budgets for all to authenticated using(public.has_permission('expenses.budgets.manage') and public.expense_scope_allows(province_id)) with check(public.has_permission('expenses.budgets.manage') and public.expense_scope_allows(province_id));
create policy requests_read on public.expense_requests for select to authenticated using(public.has_permission('expenses.view') and public.expense_scope_allows(province_id));
create policy requests_create on public.expense_requests for insert to authenticated with check(public.has_permission('expenses.create') and requested_by=auth.uid() and public.expense_scope_allows(province_id));
create policy requests_edit on public.expense_requests for update to authenticated using(requested_by=auth.uid() and status in ('draft','returned')) with check(requested_by=auth.uid());
create policy approvals_read on public.expense_approvals for select to authenticated using(public.has_permission('expenses.view'));
create policy items_read on public.expense_items for select to authenticated using(public.has_permission('expenses.view'));
create policy items_manage on public.expense_items for all to authenticated using(public.has_permission('expenses.actual') and exists(select 1 from public.expense_requests where id=expense_request_id and requested_by=auth.uid() and status in ('paid','payment_processing'))) with check(public.has_permission('expenses.actual'));
create policy payments_read on public.expense_payments for select to authenticated using(public.has_permission('expenses.view'));
create policy documents_read on public.expense_documents for select to authenticated using(public.has_permission('expenses.view'));
create policy documents_manage on public.expense_documents for all to authenticated using(uploaded_by=auth.uid()) with check(public.has_permission('expenses.create') or public.has_permission('expenses.pay') or public.has_permission('expenses.actual'));
create policy expense_audit_read on public.expense_audit_logs for select to authenticated using(public.has_permission('expenses.audit'));
create policy expense_files_read on storage.objects for select to authenticated using(bucket_id='expense-documents' and public.has_permission('expenses.view'));
create policy expense_files_insert on storage.objects for insert to authenticated with check(bucket_id='expense-documents' and (public.has_permission('expenses.create') or public.has_permission('expenses.pay') or public.has_permission('expenses.actual')));

grant execute on function public.available_budget(bigint,bigint,bigint,integer) to authenticated;
grant execute on function public.submit_expense_request(uuid) to authenticated;
grant execute on function public.decide_expense_request(uuid,text,text,numeric) to authenticated;
grant execute on function public.create_expense_payment(uuid,date,text,numeric,text,text,text,text) to authenticated;
grant execute on function public.complete_expense_request(uuid) to authenticated;
