-- Link provincial expenses to Sales visit plans and mission settlement.

alter table public.visit_plans add column if not exists planned_distance_km numeric(10,2) check (planned_distance_km is null or planned_distance_km >= 0);
alter table public.expense_requests add column if not exists visit_plan_id uuid references public.visit_plans(id) on delete restrict;
alter table public.expense_requests add column if not exists sales_id uuid references public.profiles(id) on delete restrict;
alter table public.expense_requests add column if not exists participant_count integer not null default 1 check (participant_count > 0);
alter table public.expense_requests add column if not exists estimated_distance_km numeric(10,2) not null default 0 check (estimated_distance_km >= 0);
alter table public.expense_requests add column if not exists estimated_transport_amount numeric(16,2) not null default 0 check (estimated_transport_amount >= 0);
alter table public.expense_requests add column if not exists estimated_meal_amount numeric(16,2) not null default 0 check (estimated_meal_amount >= 0);
alter table public.expense_requests add column if not exists estimated_lodging_amount numeric(16,2) not null default 0 check (estimated_lodging_amount >= 0);
alter table public.expense_requests add column if not exists estimated_other_amount numeric(16,2) not null default 0 check (estimated_other_amount >= 0);
alter table public.expense_requests add column if not exists advance_requested boolean not null default false;
alter table public.expense_requests add column if not exists settlement_due_date date;
alter table public.expense_items add column if not exists visit_plan_stop_id uuid references public.visit_plan_stops(id) on delete set null;
alter table public.expense_items add column if not exists latitude numeric(10,7) check (latitude is null or latitude between -90 and 90);
alter table public.expense_items add column if not exists longitude numeric(10,7) check (longitude is null or longitude between -180 and 180);

create table public.mission_expense_rates (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name_kh text not null,
  unit text not null check (unit in ('km','person_day','person_night','flat')),
  rate numeric(16,2) not null check (rate >= 0),
  is_active boolean not null default true,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger mission_expense_rates_updated_at before update on public.mission_expense_rates for each row execute function public.set_updated_at();

insert into public.mission_expense_rates(code,name_kh,unit,rate) values
 ('transport_km','ថ្លៃធ្វើដំណើរក្នុងមួយគីឡូម៉ែត្រ','km',0.20),
 ('meal_person_day','ថ្លៃអាហារក្នុងម្នាក់/ថ្ងៃ','person_day',10),
 ('lodging_person_night','ថ្លៃស្នាក់នៅក្នុងម្នាក់/យប់','person_night',25),
 ('mission_other','ចំណាយផ្សេងៗក្នុងបេសកកម្ម','flat',0)
on conflict(code) do nothing;

create unique index expense_requests_active_visit_plan_idx on public.expense_requests(visit_plan_id)
where visit_plan_id is not null and deleted_at is null and status not in ('rejected','cancelled','completed');
create index expense_requests_sales_idx on public.expense_requests(sales_id,request_date desc) where deleted_at is null;
create index expense_items_stop_idx on public.expense_items(visit_plan_stop_id) where visit_plan_stop_id is not null;

create or replace function public.prepare_mission_expense() returns trigger language plpgsql security definer set search_path=public as $$
declare plan_row public.visit_plans;
begin
  if new.visit_plan_id is null then return new; end if;
  select * into plan_row from public.visit_plans where id=new.visit_plan_id;
  if plan_row.id is null then raise exception 'Visit plan not found'; end if;
  if plan_row.status='cancelled' then raise exception 'Cancelled visit plan cannot have an expense request'; end if;
  new.sales_id := plan_row.assigned_to;
  new.estimated_distance_km := coalesce(plan_row.planned_distance_km,new.estimated_distance_km,0);
  if new.request_date<plan_row.start_date or new.request_date>plan_row.end_date then new.request_date:=plan_row.start_date; end if;
  new.settlement_due_date := coalesce(new.settlement_due_date,plan_row.end_date+7);
  return new;
end $$;
create trigger expense_requests_prepare_mission before insert or update of visit_plan_id,request_date on public.expense_requests for each row execute function public.prepare_mission_expense();

create or replace function public.estimate_mission_expense(p_visit_plan_id uuid,p_participant_count integer default 1)
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare plan_row public.visit_plans; mission_days integer; mission_nights integer; distance_km numeric; transport numeric; meals numeric; lodging numeric; other_amount numeric;
begin
  if not public.can_access_visit_plan(p_visit_plan_id) and not public.has_permission('expenses.view') then raise exception 'Access denied'; end if;
  select * into plan_row from public.visit_plans where id=p_visit_plan_id;
  if plan_row.id is null then raise exception 'Visit plan not found'; end if;
  mission_days:=plan_row.end_date-plan_row.start_date+1; mission_nights:=greatest(mission_days-1,0); p_participant_count:=greatest(p_participant_count,1);
  select coalesce(plan_row.planned_distance_km, sum(segment_km)*2, 0) into distance_km from (
    select 6371*acos(least(1,greatest(-1,cos(radians(latitude))*cos(radians(previous_latitude))*cos(radians(previous_longitude)-radians(longitude))+sin(radians(latitude))*sin(radians(previous_latitude))))) as segment_km
    from (select latitude,longitude,lag(latitude) over(order by stop_order) as previous_latitude,lag(longitude) over(order by stop_order) as previous_longitude from public.visit_plan_stops where visit_plan_id=p_visit_plan_id and latitude is not null and longitude is not null) stops
    where previous_latitude is not null
  ) distances;
  select coalesce(rate,0)*distance_km into transport from public.mission_expense_rates where code='transport_km' and is_active;
  select coalesce(rate,0)*p_participant_count*mission_days into meals from public.mission_expense_rates where code='meal_person_day' and is_active;
  select coalesce(rate,0)*p_participant_count*mission_nights into lodging from public.mission_expense_rates where code='lodging_person_night' and is_active;
  select coalesce(rate,0) into other_amount from public.mission_expense_rates where code='mission_other' and is_active;
  return jsonb_build_object('days',mission_days,'nights',mission_nights,'distance_km',distance_km,'participants',p_participant_count,'transport',coalesce(transport,0),'meals',coalesce(meals,0),'lodging',coalesce(lodging,0),'other',coalesce(other_amount,0),'total',coalesce(transport,0)+coalesce(meals,0)+coalesce(lodging,0)+coalesce(other_amount,0));
end $$;

create or replace view public.sales_mission_expense_summary with (security_invoker=true) as
select request.sales_id,sales.full_name as sales_name,count(*) as request_count,
  coalesce(sum(request.approved_amount),0) as approved_amount,coalesce(sum(request.amount_received),0) as paid_amount,
  coalesce(sum(request.actual_amount),0) as actual_amount,coalesce(sum(request.returned_amount),0) as returned_amount,
  count(*) filter(where request.status in ('submitted','under_review','approved','payment_processing','paid')) as active_missions,
  count(*) filter(where request.status='completed') as completed_missions
from public.expense_requests request join public.profiles sales on sales.id=request.sales_id
where request.deleted_at is null and request.sales_id is not null group by request.sales_id,sales.full_name;

alter table public.mission_expense_rates enable row level security;
create policy mission_rates_read on public.mission_expense_rates for select to authenticated using(public.has_permission('expenses.view'));
create policy mission_rates_manage on public.mission_expense_rates for all to authenticated using(public.has_permission('expenses.budgets.manage')) with check(public.has_permission('expenses.budgets.manage'));
update public.app_roles set permissions=permissions||'["expenses.view","expenses.create","expenses.submit","expenses.actual"]'::jsonb where key='sales';
update public.profiles profile set permissions=role.permissions,updated_at=now() from public.app_roles role where profile.role=role.key and profile.permissions is distinct from role.permissions;
grant execute on function public.estimate_mission_expense(uuid,integer) to authenticated;
grant select on public.sales_mission_expense_summary to authenticated;
